version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: balkanID
      PGPORT: 5432

  backend:
    build: ./backend
    entrypoint: [ "bash", "/app/run.sh" ]
    depends_on:
      - database
    restart: on-failure
    ports:
      - "8080:8080"
