// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: epic_members.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const insertEpicMember = `-- name: InsertEpicMember :one
INSERT INTO epic_members (epic_members_epic_id,epic_members_user_id)
VALUES ($1,$2)
RETURNING epic_members_user_id, epic_members_epic_id
`

type InsertEpicMemberParams struct {
	EpicMembersEpicID uuid.UUID
	EpicMembersUserID uuid.UUID
}

func (q *Queries) InsertEpicMember(ctx context.Context, arg InsertEpicMemberParams) (EpicMember, error) {
	row := q.db.QueryRowContext(ctx, insertEpicMember, arg.EpicMembersEpicID, arg.EpicMembersUserID)
	var i EpicMember
	err := row.Scan(&i.EpicMembersUserID, &i.EpicMembersEpicID)
	return i, err
}
