// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Epic struct {
	EpicID          uuid.UUID
	EpicName        string
	EpicDescription string
	EpicFeatures    string
	EpicLink        sql.NullString
	EpicStartDate   time.Time
	EpicEndDate     sql.NullTime
	EpicOwner       uuid.UUID
}

type EpicAssignment struct {
	EpicAssignmentEpicID  uuid.UUID
	EpicAssignmentUsersID uuid.UUID
	EpicAssignmentRoleID  int32
}

type EpicMember struct {
	EpicMembersUserID uuid.UUID
	EpicMembersEpicID uuid.UUID
}

type Permission struct {
	PermissionID   int32
	PermissionName string
	PermissionDesc string
}

type Role struct {
	RoleID       int32
	RoleEpicID   uuid.UUID
	RoleName     string
	RoleCategory string
}

type RolePermission struct {
	RolePermissionRoleID       int32
	RolePermissionEpicID       uuid.UUID
	RolePermissionPermissionID int32
}

type Sprint struct {
	SprintEpicID    uuid.UUID
	SprintID        int32
	SprintStartDate time.Time
	SprintEndDate   time.Time
}

type Task struct {
	TaskEpicID    uuid.UUID
	TaskID        uuid.UUID
	TaskName      string
	TaskReq       string
	TaskLog       sql.NullString
	TaskLink      sql.NullString
	TaskStartDate time.Time
	TaskEndDate   sql.NullTime
	TaskStatus    string
	TaskSprintID  sql.NullInt32
}

type TaskAssignment struct {
	TaskAssignmentTaskID  uuid.UUID
	TaskAssignmentEpicID  uuid.UUID
	TaskAssignmentUsersID uuid.UUID
	TaskAssignmentRoleID  int32
}

type User struct {
	UsersID            uuid.UUID
	UsersEmail         string
	UsersName          string
	UsersAccountStatus string
	UsersType          string
	UsersPassword      string
}

type UserAuth struct {
	UserID            uuid.UUID
	UserAuthToken     string
	UserAuthTimestamp time.Time
}
