// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: task.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :one
INSERT INTO task(task_epic_id,task_id,task_name,task_req,task_start_date,task_end_date,task_status)
VALUES ($1,$2,$3,$4,$5,$6,$7)
RETURNING task_epic_id, task_id, task_name, task_req, task_log, task_link, task_start_date, task_end_date, task_status, task_sprint_id
`

type CreateTaskParams struct {
	TaskEpicID    uuid.UUID
	TaskID        uuid.UUID
	TaskName      string
	TaskReq       string
	TaskStartDate time.Time
	TaskEndDate   sql.NullTime
	TaskStatus    string
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.TaskEpicID,
		arg.TaskID,
		arg.TaskName,
		arg.TaskReq,
		arg.TaskStartDate,
		arg.TaskEndDate,
		arg.TaskStatus,
	)
	var i Task
	err := row.Scan(
		&i.TaskEpicID,
		&i.TaskID,
		&i.TaskName,
		&i.TaskReq,
		&i.TaskLog,
		&i.TaskLink,
		&i.TaskStartDate,
		&i.TaskEndDate,
		&i.TaskStatus,
		&i.TaskSprintID,
	)
	return i, err
}

const updateTaskFull = `-- name: UpdateTaskFull :one
UPDATE task
set task_status=$3,task_link=$4,task_log=$5,task_sprint_id=$6
WHERE task_epic_id=$1 AND task_id=$2
RETURNING task_epic_id, task_id, task_name, task_req, task_log, task_link, task_start_date, task_end_date, task_status, task_sprint_id
`

type UpdateTaskFullParams struct {
	TaskEpicID   uuid.UUID
	TaskID       uuid.UUID
	TaskStatus   string
	TaskLink     sql.NullString
	TaskLog      sql.NullString
	TaskSprintID sql.NullInt32
}

func (q *Queries) UpdateTaskFull(ctx context.Context, arg UpdateTaskFullParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskFull,
		arg.TaskEpicID,
		arg.TaskID,
		arg.TaskStatus,
		arg.TaskLink,
		arg.TaskLog,
		arg.TaskSprintID,
	)
	var i Task
	err := row.Scan(
		&i.TaskEpicID,
		&i.TaskID,
		&i.TaskName,
		&i.TaskReq,
		&i.TaskLog,
		&i.TaskLink,
		&i.TaskStartDate,
		&i.TaskEndDate,
		&i.TaskStatus,
		&i.TaskSprintID,
	)
	return i, err
}

const updateTaskSprintStatus = `-- name: UpdateTaskSprintStatus :exec
UPDATE task
SET task_sprint_id=NULL
WHERE task_epic_id=$1 AND task_sprint_id=$2
`

type UpdateTaskSprintStatusParams struct {
	TaskEpicID   uuid.UUID
	TaskSprintID sql.NullInt32
}

func (q *Queries) UpdateTaskSprintStatus(ctx context.Context, arg UpdateTaskSprintStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskSprintStatus, arg.TaskEpicID, arg.TaskSprintID)
	return err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE task
SET task_status=$3
WHERE task_epic_id=$1 AND task_id=$2
RETURNING task_epic_id, task_id, task_name, task_req, task_log, task_link, task_start_date, task_end_date, task_status, task_sprint_id
`

type UpdateTaskStatusParams struct {
	TaskEpicID uuid.UUID
	TaskID     uuid.UUID
	TaskStatus string
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskStatus, arg.TaskEpicID, arg.TaskID, arg.TaskStatus)
	var i Task
	err := row.Scan(
		&i.TaskEpicID,
		&i.TaskID,
		&i.TaskName,
		&i.TaskReq,
		&i.TaskLog,
		&i.TaskLink,
		&i.TaskStartDate,
		&i.TaskEndDate,
		&i.TaskStatus,
		&i.TaskSprintID,
	)
	return i, err
}
